"""removing owner_id to PharmacyStock

Revision ID: 0630a36286b0
Revises: c792731696ea
Create Date: 2025-04-26 15:04:58.949742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0630a36286b0'
down_revision = 'c792731696ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
