"""properties fixed

Revision ID: 5592fefd4a5a
Revises: 7f84491c10bd
Create Date: 2025-03-26 21:20:48.362866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5592fefd4a5a'
down_revision = '7f84491c10bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
