"""properties updated

Revision ID: 6143af13b063
Revises: 5592fefd4a5a
Create Date: 2025-03-26 21:30:02.670462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6143af13b063'
down_revision = '5592fefd4a5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
