"""location updated

Revision ID: 6195f9fa7fa8
Revises: 6a12c3f5d308
Create Date: 2025-03-26 22:24:14.861875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6195f9fa7fa8'
down_revision = '6a12c3f5d308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
