"""add your message here

Revision ID: 6525bbe3b6cc
Revises: 9d30e4c280f0
Create Date: 2025-05-07 06:27:53.591938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6525bbe3b6cc'
down_revision = '9d30e4c280f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
