"""fixes

Revision ID: 6a12c3f5d308
Revises: 701974216f47
Create Date: 2025-03-26 22:02:15.326557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a12c3f5d308'
down_revision = '701974216f47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
