"""removed table and fixes

Revision ID: 701974216f47
Revises: e7be21eb46e6
Create Date: 2025-03-26 21:40:54.284990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701974216f47'
down_revision = 'e7be21eb46e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
