"""Frist commit

Revision ID: 7f84491c10bd
Revises: 
Create Date: 2025-03-26 21:01:25.261734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f84491c10bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pharmacy_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_pharmacies_pharmacy_id'), 'pharmacies', ['pharmacy_id'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.pharmacy_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_location_id'), 'locations', ['location_id'], unique=False)
    op.create_table('medicines',
    sa.Column('medic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.pharmacy_id'], ),
    sa.PrimaryKeyConstraint('medic_id')
    )
    op.create_index(op.f('ix_medicines_medic_id'), 'medicines', ['medic_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.pharmacy_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('medic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medic_id'], ['medicines.medic_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=False)
    op.create_table('pharmacy_stock',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('medic_id', sa.Integer(), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medic_id'], ['medicines.medic_id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.pharmacy_id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index(op.f('ix_pharmacy_stock_stock_id'), 'pharmacy_stock', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_stock_stock_id'), table_name='pharmacy_stock')
    op.drop_table('pharmacy_stock')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_medicines_medic_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_locations_location_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_pharmacies_pharmacy_id'), table_name='pharmacies')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
