"""updated Stocks

Revision ID: 9761f023514e
Revises: 1895cad9427a
Create Date: 2025-04-26 14:46:50.532729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9761f023514e'
down_revision = '1895cad9427a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
