"""new updates

Revision ID: 9d30e4c280f0
Revises: 0e5340930479
Create Date: 2025-05-06 16:03:52.917013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d30e4c280f0'
down_revision = '0e5340930479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
