"""updated Stocks Add MedicId

Revision ID: c792731696ea
Revises: 9761f023514e
Create Date: 2025-04-26 14:56:23.554153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c792731696ea'
down_revision = '9761f023514e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
