"""Adding pharmacyId onMedicines

Revision ID: e4eb3388c09a
Revises: efea2227f4ca
Create Date: 2025-04-28 23:02:14.316585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4eb3388c09a'
down_revision = 'efea2227f4ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
