"""new table added and new fixis

Revision ID: e7be21eb46e6
Revises: 6143af13b063
Create Date: 2025-03-26 21:39:05.421694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7be21eb46e6'
down_revision = '6143af13b063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('medicines_pharmacy_id_fkey', 'medicines', type_='foreignkey')
    op.drop_column('medicines', 'pharmacy_id')
    op.drop_constraint('patients_medic_id_fkey', 'patients', type_='foreignkey')
    op.drop_column('patients', 'medic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('medic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('patients_medic_id_fkey', 'patients', 'medicines', ['medic_id'], ['medic_id'])
    op.add_column('medicines', sa.Column('pharmacy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('medicines_pharmacy_id_fkey', 'medicines', 'pharmacies', ['pharmacy_id'], ['pharmacy_id'])
    # ### end Alembic commands ###
