"""removing owner_id duplicate to PharmacyStock

Revision ID: efea2227f4ca
Revises: 0630a36286b0
Create Date: 2025-04-26 15:11:15.772769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efea2227f4ca'
down_revision = '0630a36286b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
